### ISSUE TITLE
lobby-chat missing

### ISSUE THREAD

**Issue by Alvo** [Poweruser/OFPMonitor#2]
a lobby-chat as in ewarzone would be great

like here:
http://www.ewarzone.com/images/ss_full.jpg

**Comment by Poweruser** [comment]
1. replace "missing" with "request".
2. aren't there already enough means of communication outside of the game?
   teamspeak, skype, icq, msn, website forums dedicated to ofp, ...
3. there are also a few issues with this
   a) the easiest way to do it, is to write an pure chat server application which runs the chat, and with ofpmonitor you connect as client. Simple, but requires a server which is constantly online. I won't host one and I can not expect anyone else to do it.
   b) the chat server side is built into ofpmonitor and a client can host chats. But that would require the one hosting to forward a port on his firewall/router, so that others are able to connect to him. It's also necessary to find a way to propagate the client-host's internet address to all other ofpmonitor clients, as they cant connect to an address they dont know. And that still requires some sort of central instance where the clienthost can deposit his internet address and other's can look it up. This could be done with an already 24/7 running ftp-server, still someone else's resource i can not rely on.

**Comment by Alvo** [comment]
Answer:
2. communication channels outside OFP / OFPMonitor are nice, but no true replacement. When remembering my EWarzone days, i cannot imagine that these other communication channels would have kept the community alive and networked like that. But other communication channels are of course used in the same intensity besides the lobby-client.
1. a) defenitely go for the centralized server approach. {KG} Killer would host it (he offered to do this), but there can be multiple fallback-server-urls configured inside lobby-client.

b) P2P is awesome and never really works. You can implement a sophisticated "firewall-traversal" algorithm that tricks around firewalls, even better than skype does this (like Hamachi firewall traversal which is better). but this is not worth the effort i think.

For player name we could use the registry key:
HKEY_CURRENT_USER\Software\Codemasters\Operation Flashpoint
keyname: "Player Name"

btw i ansered late because my internet broke down and it just recovered :D

Chers
Owe (Alvo)

**Comment by Alvo** [comment]
There is another possibility, you can use IRC for Lobby-chat, there are some irc libraries written in C out there:
http://libircclient.sourceforge.net/

Chers
Al

**Comment by simi** [comment]
+1 for IRC

But I can host server side application if you will need.

**Comment by Poweruser** [comment]
if you were tracking the commits, you'd notice that the chat made it in already. current server for testing is   irc.freenode.net:6666   channel:operationflashpoint1

**Comment by simi** [comment]
I noticed few secs ago :(

**Comment by Poweruser** [comment]
added in version 1.40
For discussing the implemented chat open a new Issue please
